### ISSUE TITLE
Which codebase you recommend more, TracKit or SOTS?

### ISSUE THREAD

**Issue by LouisShen233** [JudasDie/SOTS#24]
Since these two both cover the whole Ocean method.

**Comment by JudasDie** [comment]
> Since these two both cover the whole Ocean method.

Hi, SOTS is recommended. Recently, I'm re-organizing this codebase to make it neater, since it is built two years ago (the current code is pretty dirty in my view).  Besides, this codebase will support our ICCV21 paper (if accepted). About one week later, I will upload the new version for SOT, then MOT later. The ICCV code will be released at the end of this month (if accepted).

**Comment by LouisShen233** [comment]
> > Since these two both cover the whole Ocean method.
> 
> Hi, SOTS is recommended. Recently, I'm re-organizing this codebase to make it neater, since it is built two years ago (the current code is pretty dirty in my view). Besides, this codebase will support our ICCV21 paper (if accepted). About one week later, I will upload the new version for SOT, then MOT later. The ICCV code will be released at the end of this month (if accepted).

Ok noted. Thank you! Looking forward to the new version of SOTS.

**Comment by JudasDie** [comment]
New codebase has been released. Thanks for the interest.
